FROM node:18

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install


COPY middleware ./middleware
COPY API-doc ./API-doc
COPY db.js ./db.js
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

COPY microservices/audit-log-service/ ./

EXPOSE 3005

#CMD ["node", "server.js"]
CMD ["/wait-for-it.sh", "rabbitmq:5672", "--", "node", "server.js"]